//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discuz.Web.Admin
{


    public partial class mymenumanage
    {
        protected global::Discuz.Control.Button DelRec;
        protected global::Discuz.Control.Button addmenu;
        protected global::Discuz.Control.Button SaveMyMenu;
        protected global::Discuz.Control.DataGrid DataGrid1;
        protected global::Discuz.Control.TextBox atext;
        protected global::Discuz.Control.TextBox ahref;
        protected global::Discuz.Control.TextBox aonclick;
        protected global::Discuz.Control.TextBox atarget;
        protected global::Discuz.Control.Hint Hint1;
    }
}
