//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discuz.Web.Admin
{


    public partial class aggregation_rotatepic
    {

        protected global::Discuz.Control.Button DelRec;
        protected global::Discuz.Control.Button addrota;
        protected global::Discuz.Control.DataGrid DataGrid1;
        protected global::Discuz.Control.TextBox rotaimg;
        protected global::Discuz.Control.TextBox url;
        protected global::Discuz.Control.TextBox titlecontent;
        protected global::Discuz.Control.Button SaveRotatepic;
        protected global::Discuz.Control.Hint Hint1;
    }
}
