//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discuz.Web.Admin {
    
    
    public partial class registerandvisit {
        
        /// <summary>
        /// Form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm Form1;
        
        /// <summary>
        /// regstatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Discuz.Control.RadioButtonList regstatus;
        
        /// <summary>
        /// realnamesystem control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Discuz.Control.RadioButtonList realnamesystem;
        
        /// <summary>
        /// censoruser control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Discuz.Web.Admin.TextareaResize censoruser;
        
        /// <summary>
        /// regverify control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Discuz.Control.RadioButtonList regverify;
        
        /// <summary>
        /// accessemail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Discuz.Web.Admin.TextareaResize accessemail;
        
        /// <summary>
        /// censoremail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Discuz.Web.Admin.TextareaResize censoremail;
        
        /// <summary>
        /// regctrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Discuz.Control.TextBox regctrl;
        
        /// <summary>
        /// mycheck control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator mycheck;
        
        /// <summary>
        /// newbiespan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Discuz.Control.TextBox newbiespan;
        
        /// <summary>
        /// RegularExpressionValidator1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator1;
        
        /// <summary>
        /// doublee control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Discuz.Control.RadioButtonList doublee;
        protected global::Discuz.Control.RadioButtonList emaillogin;
        /// <summary>
        /// ipregctrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Discuz.Web.Admin.TextareaResize ipregctrl;
        
        /// <summary>
        /// rules control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Discuz.Control.RadioButtonList rules;
        
        /// <summary>
        /// rulestxt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Discuz.Web.Admin.TextareaResize rulestxt;
        
        /// <summary>
        /// welcomemsg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Discuz.Control.RadioButtonList welcomemsg;
        
        /// <summary>
        /// welcomemsgtxt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Discuz.Web.Admin.TextareaResize welcomemsgtxt;
        
        /// <summary>
        /// Hint1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Discuz.Control.Hint Hint1;
        
        /// <summary>
        /// hideprivate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Discuz.Control.RadioButtonList hideprivate;
        
        /// <summary>
        /// ipaccess control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Discuz.Web.Admin.TextareaResize ipaccess;
        
        /// <summary>
        /// ipdenyaccess control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Discuz.Web.Admin.TextareaResize ipdenyaccess;
        
        /// <summary>
        /// adminipaccess control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Discuz.Web.Admin.TextareaResize adminipaccess;
        
        /// <summary>
        /// SaveInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Discuz.Control.Button SaveInfo;

        protected global::Discuz.Control.TextBox invitecodeexpiretime;

        protected global::Discuz.Control.TextBox addextcreditsline;

        protected global::Discuz.Control.TextBox invitecodemaxcount;

        protected global::Discuz.Control.TextBox invitecodeusermaxbuy;

        protected global::Discuz.Control.TextBox invitecodeusercreateperday;

        protected global::Discuz.Control.TextBox invitecodeprice0;
        protected global::Discuz.Control.TextBox invitecodeprice1;
        protected global::Discuz.Control.TextBox invitecodeprice2;
        protected global::Discuz.Control.TextBox invitecodeprice3;
        protected global::Discuz.Control.TextBox invitecodeprice4;
        protected global::Discuz.Control.TextBox invitecodeprice5;
        protected global::Discuz.Control.TextBox invitecodeprice6;
        protected global::Discuz.Control.TextBox invitecodeprice7;

        //protected global::System.Web.UI.HtmlControls.HtmlTextArea invitationuserdescriptionmessage;
        //protected global::System.Web.UI.HtmlControls.HtmlTextArea invitationvisitordescriptionmessage;
        //protected global::System.Web.UI.HtmlControls.HtmlTextArea invitationemailmodelmessage;
        //protected global::Discuz.Web.Admin.OnlineEditor invitationemailmodel;
        protected global::Discuz.Web.Admin.OnlineEditor invitationuserdescription;
        protected global::Discuz.Web.Admin.OnlineEditor invitationvisitordescription;
        protected global::Discuz.Web.Admin.OnlineEditor invitationemailmodel;
        /// <summary>
        /// passwordmode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Discuz.Control.RadioButtonList passwordmode;

        /// <summary>
        /// CookieDomain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Discuz.Control.TextBox CookieDomain;
    }
}
