document.write("    <div style=\"width: 700px;\">");
document.write("    <div id=\"SilverlightControlHost\" class=\"silverlightHost\" style=\"float:left;\" >");
document.write("    <\/div>");
document.write("    <div style=\"width:300px; height:480px; padding:20px; margin-top:100px; float: right;\">");
document.write("        <div id=\"PieCaption0\" style=\"border:none; background:Transparent; padding:3px 3px 3px 3px; vertical-align:baseline;\">");
document.write("            <div id=\"dot0\" style=\"border:solid 1px #999999; width:12px; height:12px; background-color:#83d3ed; float:left; margin-top:4px;\">&nbsp;<\/div>");
document.write("            <span id=\"title0\" style=\"font-family:Arial; font-size:12px; margin-left: 10px; color:#666666;\">Pie Title00<\/span>");
document.write("        <\/div>");
document.write("        <div id=\"PieCaption1\" style=\"border:none; background:Transparent; padding:3px 3px 3px 3px; vertical-align:baseline;\">");
document.write("            <div id=\"dot1\" style=\"border:solid 1px #999999; width:12px; height:12px; background-color:#7fc7bc; float:left; margin-top:4px;\">&nbsp;<\/div>");
document.write("            <span id=\"title1\" style=\"font-family:Arial; font-size:12px; margin-left: 10px; color:#666666;\">Pie Title01<\/span>");
document.write("        <\/div>");
document.write("        <div id=\"PieCaption2\" style=\"border:none; background:Transparent; padding:3px 3px 3px 3px; vertical-align:baseline;\">");
document.write("            <div id=\"dot2\" style=\"border:solid 1px #999999; width:12px; height:12px; background-color:#4ab4c1; float:left; margin-top:4px;\">&nbsp;<\/div>");
document.write("            <span id=\"title2\" style=\"font-family:Arial; font-size:12px; margin-left: 10px; color:#666666;\">Pie Title02<\/span>");
document.write("        <\/div>");
document.write("        <div id=\"PieCaption3\" style=\"border:none; background:Transparent; padding:3px 3px 3px 3px; vertical-align:baseline;\">");
document.write("            <div id=\"dot3\" style=\"border:solid 1px #999999; width:12px; height:12px; background-color:#edf6f1; float:left; margin-top:4px;\">&nbsp;<\/div>");
document.write("            <span id=\"title3\" style=\"font-family:Arial; font-size:12px; margin-left: 10px; color:#666666;\">Pie Title03<\/span>");
document.write("        <\/div>");
document.write("        <div id=\"PieCaption4\" style=\"border:none; background:Transparent; padding:3px 3px 3px 3px; vertical-align:baseline;\">");
document.write("            <div id=\"dot4\" style=\"border:solid 1px #999999; width:12px; height:12px; background-color:#b5e656; float:left; margin-top:4px;\">&nbsp;<\/div>");
document.write("            <span id=\"title4\" style=\"font-family:Arial; font-size:12px; margin-left: 10px; color:#666666;\">Pie Title04<\/span>");
document.write("        <\/div>");
document.write("        <div id=\"PieCaption5\" style=\"border:none; background:Transparent; padding:3px 3px 3px 3px; vertical-align:baseline;\">");
document.write("            <div id=\"dot5\" style=\"border:solid 1px #999999; width:12px; height:12px; background-color:#97ca2d; float:left; margin-top:4px;\">&nbsp;<\/div>");
document.write("            <span id=\"title5\" style=\"font-family:Arial; font-size:12px; margin-left: 10px; color:#666666;\">Pie Title05<\/span>");
document.write("        <\/div>");
document.write("        <div id=\"PieCaption6\" style=\"border:none; background:Transparent; padding:3px 3px 3px 3px; vertical-align:baseline;\">");
document.write("            <div id=\"dot6\" style=\"border:solid 1px #999999; width:12px; height:12px; background-color:#b7ca79; float:left; margin-top:4px;\">&nbsp;<\/div>");
document.write("            <span id=\"title6\" style=\"font-family:Arial; font-size:12px; margin-left: 10px; color:#666666;\">Pie Title06<\/span>");
document.write("        <\/div>");
document.write("        <div id=\"PieCaption7\" style=\"border:none; background:Transparent; padding:3px 3px 3px 3px; vertical-align:baseline;\">");
document.write("            <div id=\"dot7\" style=\"border:solid 1px #999999; width:12px; height:12px; background-color:#98cc85; float:left; margin-top:4px;\">&nbsp;<\/div>");
document.write("            <span id=\"title7\" style=\"font-family:Arial; font-size:12px; margin-left: 10px; color:#666666;\">Pie Title07<\/span>");
document.write("        <\/div>");
document.write("        <div id=\"PieCaption8\" style=\"border:none; background:Transparent; padding:3px 3px 3px 3px; vertical-align:baseline;\">");
document.write("            <div id=\"dot8\" style=\"border:solid 1px #999999; width:12px; height:12px; background-color:#5dd68f; float:left; margin-top:4px;\">&nbsp;<\/div>");
document.write("            <span id=\"title8\" style=\"font-family:Arial; font-size:12px; margin-left: 10px; color:#666666;\">Pie Title08<\/span>");
document.write("        <\/div>");
document.write("        <div id=\"PieCaption9\" style=\"border:none; background:Transparent; padding:3px 3px 3px 3px; vertical-align:baseline;\">");
document.write("            <div id=\"dot9\" style=\"border:solid 1px #999999; width:12px; height:12px; background-color:#e6e7d7; float:left; margin-top:4px;\">&nbsp;<\/div>");
document.write("            <span id=\"title9\" style=\"font-family:Arial; font-size:12px; margin-left: 10px; color:#666666;\">Pie Title09<\/span>");
document.write("        <\/div>");
document.write("    <\/div>");
document.write("    <\/div>");
_attachEvent(window, "load", function(){createSilverlight();});
